package com.sq.caa.rag;

import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Format-independent tests for "does this line look like a section heading?".
 *
 * <p>Shared by both parsers. The DOCX parser reaches for these only when a document carries no
 * heading styles at all; the PDF parser uses them as the fallback behind its font-size and
 * boldness measurements, because a large share of real policy PDFs are generated by tools that
 * emit no structure tags whatsoever.
 */
public final class HeadingHeuristics {

    /** Longest line still plausible as a heading. */
    public static final int MAX_HEADING_LENGTH = 140;

    /** Most words a heading is allowed to have. */
    public static final int MAX_HEADING_WORDS = 18;

    /**
     * {@code 3}, {@code 3.}, {@code 3.1}, {@code 4.2.1)} followed by title text. The numbering must
     * be followed by whitespace, so "3.5 million" style prose is not mistaken for a heading - that
     * case is excluded by the word and punctuation tests in {@link #looksLikeHeading(String)}.
     */
    private static final Pattern NUMBERED_HEADING =
            Pattern.compile("^\\s*(\\d{1,2}(?:\\.\\d{1,2}){0,3})[.)]?\\s+(\\S.*)$");

    /** {@code Section 4}, {@code Article II}, {@code Appendix B}, {@code Annex 1}, {@code Part 3}. */
    private static final Pattern LABELLED_HEADING = Pattern.compile(
            "^\\s*(?:section|article|appendix|annex|chapter|part|schedule)\\s+"
                    + "(?:\\d{1,3}|[ivxlcdm]{1,7})\\b.*$",
            Pattern.CASE_INSENSITIVE);

    private static final Pattern BULLET_START =
            Pattern.compile("^\\s*(?:[-•–—*·▪●◦‣]"
                    + "|\\(?[a-z]\\)|\\(?[ivx]{1,4}\\))\\s+\\S.*$");

    private HeadingHeuristics() {
    }

    /** True when the line is short enough and shaped like a title rather than a sentence. */
    public static boolean looksLikeHeading(String line) {
        String trimmed = line == null ? "" : line.strip();
        if (trimmed.isEmpty() || trimmed.length() > MAX_HEADING_LENGTH) {
            return false;
        }
        if (isNumberedHeading(trimmed) || LABELLED_HEADING.matcher(trimmed).matches()) {
            return true;
        }
        if (isBullet(trimmed)) {
            return false;
        }
        if (countWords(trimmed) > MAX_HEADING_WORDS) {
            return false;
        }
        return isAllCaps(trimmed) && trimmed.length() <= 80 && countWords(trimmed) <= 10;
    }

    /** True for {@code 2.1 Transaction thresholds} and friends. */
    public static boolean isNumberedHeading(String line) {
        String trimmed = line == null ? "" : line.strip();
        if (trimmed.isEmpty() || trimmed.length() > MAX_HEADING_LENGTH) {
            return false;
        }
        Matcher matcher = NUMBERED_HEADING.matcher(trimmed);
        if (!matcher.matches()) {
            return false;
        }
        String title = matcher.group(2);
        // "3. The customer paid 4,000 USD to ..." is a sentence, not a heading.
        return countWords(title) <= MAX_HEADING_WORDS && !endsLikeSentence(title);
    }

    /** Depth implied by a numbered heading: {@code 4} is level 1, {@code 4.2} level 2, and so on. */
    public static int numberedHeadingLevel(String line) {
        Matcher matcher = NUMBERED_HEADING.matcher(line == null ? "" : line.strip());
        if (!matcher.matches()) {
            return 0;
        }
        return (int) matcher.group(1).chars().filter(c -> c == '.').count() + 1;
    }

    /** True when the line opens a bullet or lettered list item. */
    public static boolean isBullet(String line) {
        return line != null && BULLET_START.matcher(line).matches();
    }

    /** True when the line reads like the end of a sentence rather than a title. */
    public static boolean endsLikeSentence(String line) {
        if (line == null || line.isBlank()) {
            return false;
        }
        char last = line.strip().charAt(line.strip().length() - 1);
        return last == '.' || last == ',' || last == ';';
    }

    /** True when every cased letter in the line is upper case and there are at least three of them. */
    public static boolean isAllCaps(String line) {
        if (line == null) {
            return false;
        }
        int letters = 0;
        for (int i = 0; i < line.length(); i++) {
            char c = line.charAt(i);
            if (Character.isLetter(c)) {
                letters++;
                if (Character.isLowerCase(c)) {
                    return false;
                }
            }
        }
        return letters >= 3;
    }

    public static int countWords(String text) {
        if (text == null || text.isBlank()) {
            return 0;
        }
        return text.strip().split("\\s+").length;
    }

    /** Trims a heading down to what should be stored as {@code section_title}. */
    public static String normaliseTitle(String raw) {
        if (raw == null) {
            return "";
        }
        String title = raw.replaceAll("\\s+", " ").strip();
        while (!title.isEmpty()) {
            char last = title.charAt(title.length() - 1);
            if (last == ':' || last == '.' || last == '…') {
                title = title.substring(0, title.length() - 1).strip();
            } else {
                break;
            }
        }
        return capHeadingLength(title);
    }

    /**
     * Caps a heading at {@link #MAX_HEADING_LENGTH}.
     *
     * <p>A heading is prepended to <em>every</em> window cut from its section and is copied into
     * every chunk's {@code section_title} metadata, so its length multiplies through the whole
     * document. Nothing in a {@code .docx} stops an author from applying {@code Heading 2} to a
     * page of prose, and the heuristic length guards do not apply once a document has any styled
     * heading at all - so the cap is enforced here, at the one point every parser funnels through.
     * The cut is made at a word boundary where one is close enough, and marked with an ellipsis so
     * a reader can see the title was shortened.
     */
    public static String capHeadingLength(String title) {
        if (title == null) {
            return "";
        }
        String trimmed = title.strip();
        if (trimmed.length() <= MAX_HEADING_LENGTH) {
            return trimmed;
        }
        String cut = trimmed.substring(0, MAX_HEADING_LENGTH - 1);
        int lastSpace = cut.lastIndexOf(' ');
        if (lastSpace >= MAX_HEADING_LENGTH / 2) {
            cut = cut.substring(0, lastSpace);
        }
        return cut.stripTrailing() + '…';
    }

    /** Turns a file name into a readable fallback title: {@code aml-policy_v2.pdf} to {@code Aml policy v2}. */
    public static String titleFromFilename(String filename) {
        if (filename == null || filename.isBlank()) {
            return "Untitled document";
        }
        String base = filename;
        int slash = Math.max(base.lastIndexOf('/'), base.lastIndexOf('\\'));
        if (slash >= 0) {
            base = base.substring(slash + 1);
        }
        int dot = base.lastIndexOf('.');
        if (dot > 0) {
            base = base.substring(0, dot);
        }
        base = base.replaceAll("[_\\-]+", " ").replaceAll("\\s+", " ").strip();
        if (base.isEmpty()) {
            return "Untitled document";
        }
        return base.substring(0, 1).toUpperCase(Locale.ROOT) + base.substring(1);
    }
}
